Cor 16 placer les champions dans la m moire
M0ugou-club/corewar pull request #35
Opened 2023-05-22 16:23 UTC by haihuac03

2023-05-22 16:33 UTC, Castres-Raphael approved these changes

2023-05-22 16:33 UTC, Castres-Raphael commented on corewar/champion/put_champion.c
> +// int main(void)
eneleve le main

2023-05-22 16:33 UTC, Castres-Raphael commented on corewar/champion/put_champion.c
> +process_t *add_champ(process_t *liste, char *id, char *code, int index)
remove cette fonction, on aura deja les champions de crées

2023-05-22 16:33 UTC, Castres-Raphael commented on corewar/champion/put_champion.c
> +        // if (get_mem_value(arena, index + 1) == 0) {
enelève les commentaires et l'erreur se produit quand la valeur n'esr pas égale à 0, la tu met une erreur si la valeur est a 0

2023-05-22 16:34 UTC, Castres-Raphael requested changes
voir commentaires

2023-05-23 08:04 UTC, soualmatthias approved these changes

2023-05-23 08:04 UTC, merged