Cor 4 compiler le header
M0ugou-club/corewar pull request #5
Opened 2023-05-15 11:00 UTC by albe2

fill the structure header with error handling

2023-05-15 15:07 UTC, soualmatthias commented on asm/src/compil_header.c
> +int get_name(file_t *file, header_s *header)
STATIC

2023-05-15 15:08 UTC, soualmatthias commented on asm/src/compil_header.c
> +int get_comment(file_t *file, header_s *header)
STATIC

2023-05-15 15:09 UTC, soualmatthias commented on asm/src/compil_header.c
> +static int count_text(file_t *file, char *text)
CONST CHAR * ??????????

2023-05-15 15:10 UTC, soualmatthias requested changes
rien de grave bébou

2023-05-16 09:52 UTC, Castres-Raphael requested changes
valeur à assigner

2023-05-16 09:52 UTC, Castres-Raphael commented on asm/src/compil_header.c
> +        header->prog_size;
assigne la valeur

2023-05-17 12:22 UTC, soualmatthias approved these changes

2023-05-17 12:45 UTC, Castres-Raphael approved these changes

2023-05-17 12:45 UTC, merged